name: reboot_common
version: "1.0.0"

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <=4.0.0"

dependencies:
  win32: ^5.5.4
  ffi: ^2.1.3
  path: ^1.9.0
  http: ^1.2.2
  crypto: ^3.0.5
  archive: ^3.6.1
  ini: ^2.1.0
  shelf_proxy: ^1.0.2
  sync: ^0.3.0
  uuid: ^4.5.1
  shelf_web_socket: ^2.0.0
  version: ^3.0.2
  synchronized: ^3.3.0+3

dev_dependencies:
  flutter_lints: ^5.0.0